### ISSUE TITLE
`run_pipeline` fails when no index exists

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb-data-pipeline#20]
## Current behavior

Executing these steps:

```
> docker-compose up -d
> cd path/to/repo
> workon ccdb5
> python run_pipeline -c config.ini
```

results in this:

```
2017-09-18 12:44:09,090 - complaint - INFO - Creating Elasticsearch Connection
2017-09-18 12:44:09,091 - complaint - INFO - Testing to ensure Socrata index is stable or growing
Traceback (most recent call last):
  File "run_pipeline.py", line 104, in <module>
    main()
  File "run_pipeline.py", line 101, in main
    download_and_index(c)
  File "run_pipeline.py", line 84, in download_and_index
    test_index_growing(es, index_name)
  File "run_pipeline.py", line 49, in test_index_growing
    res = es.search(index=index_name, doc_type=DOC_TYPE_NAME)
  File "python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "python2.7/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```

## Expected behavior

It should fail quietly when no index has been established yet

**Comment by chosak** [comment]
For anyone else that encounters this, you can comment out [this line](https://github.com/cfpb/ccdb-data-pipeline/blob/04495ed452a44d561faaed929c93d7d81094f9ee/run_pipeline.py#L91) on your first run to skip the initial index check. The index will be created properly the first time data is loaded.

**Comment by JeffreyMFarley** [comment]
This pipeline no longer uses `run_pipeline.py` or the "always increasing" check
